### ISSUE TITLE
Business Address Schema Doesn't Show Up

### ISSUE THREAD

**Issue by notoveryet** [Creare/CreareSEO#27]
Hi, I have the latest version of the extension but the Business Address Schema doesn't show up anywhere in the code. I filled out all the fields but it's nowhere to be found. Please let me know.

**Comment by adampmoss** [comment]
Hello,

Currently, this schema is not supposed to show up anywhere in the code. It is there for web developers to enter business details in case they wish to bring that information out anywhere. Leave this with me and I'll look into adding something shortly.

**Comment by adampmoss** [comment]
I've just released an update the will bring out these details in JSON-LD Organization schema if enabled.

**Comment by notoveryet** [comment]
I just tried enabling the Organization schema but the JSON is still not showing up.

**Comment by adampmoss** [comment]
If you email me details of the website to adam [at] creare.co.uk I'll take a look.

**Comment by notoveryet** [comment]
I think the creareseo/business/schema.phtml is missing from the master. sorry I am not sure if I even need this but just checking functionality.

**Comment by adampmoss** [comment]
You're right, it is needed and it missing for some reason.

**Comment by adampmoss** [comment]
Some issues with Git meant a load of new files didn't get pushed. Give it a try now.

**Comment by notoveryet** [comment]
not everything works perfectly! Thanks again, Adam.
